use_frameworks!

target 'ComponentLibPod_Example' do
  pod 'ComponentLibPod', :path => '../'

  target 'ComponentLibPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
